src/Entity/Command.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandRepository")
 */
class Command
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email."
     * )
     */
    private $email;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Product")
     */
    private $products;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAT;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
        }

        return $this;
    }

    public function getCreatedAT(): ?\DateTimeInterface
    {
        return $this->createdAT;
    }

    public function setCreatedAT(\DateTimeInterface $createdAT): self
    {
        $this->createdAT = $createdAT;

        return $this;
    }

    public function getPrice()
    {
        $somme=0;

        foreach($this->products as $product){
            $somme += $product->getPrice();
        }

        return $somme;
    } 


    public function getNbProduct()
    {
        return $this->products->count();
    } 
}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use App\Entity\Command;
use App\Entity\Product;
use App\Form\CommandType;
use App\Repository\ProductRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Exception\InvalidCsrfTokenException;

class PanierController extends AbstractController
{
    /**
     * @Route("/panier", name="panier")
     */
    public function index(SessionInterface $session,Request $request,ProductRepository $productRepository)
    {
        $command = new Command();
        $panier = $session->get('panier', []);
        $total=0;

        $panierForm = $this->createForm(CommandType::class, $command);
        $panierForm->handleRequest($request);

        if ($panierForm->isSubmitted() && $panierForm->isValid()) {
            $command->setCreatedAt(new \DateTime);
            foreach($panier as $id=>$quantity){
                $command->addProduct($productRepository->find($id));
            }
            $manager = $this->getDoctrine()->getManager();
            $manager->persist($command);  
            $manager->flush();
            $session->clear();
            $this->addFlash('success',"La commande est validée !");
            return $this->redirectToRoute('panier');
        }

        foreach($panier as $key => $produit) {
            $total = $total + $produit->getPrice();
        }
        return $this->render('panier/index.html.twig', [
            'panier' => $panier,
            'total' => $total,
            'panierForm' => $panierForm->createView() 
        ]);
    }


    /**
     * @Route("/panier/add/{id}", name="panier.add")
     */
    public function add($id, SessionInterface $session,Product $product,ProductRepository $productRepository)
    {
        if ($product) {
            $panier = $session->get('panier', []);

            if($panier){
                $panier[$id] = $productRepository->find($id);
                $this->addFlash('success',"La produit est ajouté !");
            }else{
                $pannier=array();
                $panier[$id] = $productRepository->find($id);
                $this->addFlash('success',"La produit est ajouté !");
            }
            $session->set('panier', $panier);
            return $this->json('ok', 200);
        }else{
            return $this->json('nok', 404);
        }
    }

    /**
     * @Route("/panier/delete/{id}", name="panier.delete")
     */
    public function delete($id, SessionInterface $session,Product $product,ProductRepository $productRepository,Request $request)
    {
        if ($product) {
            $panier = $session->get('panier', []);
            $csrfToken = $request->request->get('token');

            if ($this->isCsrfTokenValid('delete-item', $csrfToken)) {
                if($panier){
                    unset($panier[$id]);
                    $session->set('panier', $panier);
                    $this->addFlash('danger',"La produit est suprimé !");
                }
                return $this->redirectToRoute('panier');
            }else{
                throw new InvalidCsrfTokenException();
            }
        }
    }
}

templates/panier/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Votre panier</h1>
    <table class="table ">
        <thead>
            <tr>
                <th scope="col">Nom du produit</th>
                <th scope="col">Quantité</th>
                <th scope="col">Prix</th>
            </tr>
        </thead>
        {% for produit in panier %}
        <tr>
            <td>{{produit.name}}
                <form method="POST" action="{{ path('panier.delete', {id : produit.id}) }}" onsubmit="return confirm('Etes-vous sûr de supprimer cet article ?')">
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="token" value="{{ csrf_token('delete-item') }}">
                    <input type="submit" class="btn btn-danger" value="Supprimer">
                </form>
            </td>
            <td>1</td>
            <td>{{produit.price}}€</td>
            
        </tr>
        {% endfor %}
    </table>
    Total prix panier : {{total}}€
</div>

{{ form_start(panierForm) }}
    <div class="form-group">
        <label for="panier.email">Email</label>
        {{ form_row(panierForm.email) }}
        <small class="text-danger">
            {{ form_errors(panierForm.email) }}
        </small>
    </div>
    <button type="submit" class="btn btn-primary">
        Passer la commande
    </button>
{{ form_end(panierForm) }}

{% endblock %}